### ISSUE TITLE
how to run ?

### ISSUE THREAD

**Issue by itcreator** [mulesoft/oas-raml-converter#13]
```
oas-raml-converter --from OAS --to RAML10 api_doc.yml > raml.yml
```
```
/usr/bin/env: ‘node --harmony’: No such file or directory
```

**Comment by glodieu** [comment]
README updated. please try again. Thanks.

**Comment by serboctor** [comment]
Which part of the readme addresses this? and does that mean I can't install using ` npm install -g oas-raml-converter`? because that doesnt work for me and gives this same error.

**Comment by torsjonas** [comment]
Getting this in Alpine Linux running in a Docker container. Seems that passing the --harmony flag won't work on some Linux distributions, as described for example here:
https://github.com/lambtron/emojipacks/issues/94

What node harmony features are actually required by this CLI? Could the harmony flag be removed?
