### ISSUE TITLE
Invalid --from spec given. See --help.

### ISSUE THREAD

**Issue by jfernandezrico** [mulesoft/oas-raml-converter#21]
Hi,

When I run 
`oas-raml-converter --from raml10 --to swagger Stocks.raml`
I get next message
`Invalid --from spec given. See --help.`

**Comment by tomasmateus** [comment]
Hi, in this case the new correct formats to use are RAML and OAS20. I'll make sure to update the README.md

**Comment by jfernandezrico** [comment]
Ok. Thank you Tomas. Dont' forget to upgrade --help output for oas-raml-converter
