### ISSUE TITLE
Cannot read properly 'hasOwnProperty' of null

### ISSUE THREAD

**Issue by NathanNam** [mulesoft/oas-raml-converter#8]
While I tried to convert this OAS to RAML through https://mulesoft.github.io/oas-raml-converter/#, I got the following error.

<img width="1193" alt="screen shot 2017-06-02 at 3 04 14 pm" src="https://cloud.githubusercontent.com/assets/8757699/26749260/8e3538f0-47dd-11e7-856b-8d6ee72d4f45.png">

[Zoura.yaml.zip](https://github.com/mulesoft/oas-raml-converter/files/1049250/Zoura.yaml.zip) You can find the original OAS file here. https://www.zuora.com/wp-content/themes/zuora/yaml/swagger.yaml?v-5.2.1

**Comment by eric-jahn** [comment]
I'm getting this same error, except I am trying to convert RAML .8 to RAML 1.0.  [Here is a link](https://github.com/hmis-api/user-service-api/blob/master/api-markup/api.0.8.raml) to the original RAML .8 I am trying to convert.  Here is the [html](https://hmis-api.github.io/user-service-api/) for it made with raml2html.  It has no warnings or errors in the Mulesoft AnyPoint API Designer.
![raml](https://user-images.githubusercontent.com/4115079/30409274-0f4809fa-98d2-11e7-99f5-36d707d3f3c2.png).  There is no line number in the error output that I can debug with, so I don't know where to start.

**Comment by atillay** [comment]
I'm getting the same error : Cannot read property 'hasOwnProperty' .

I'm using an export from API Platform (`php bin/console api:openapi:export --spec-version=2`)

I tried : 
- `oas-raml-converter --from OAS20 --to RAML ./export.json > export.raml`
- The online tool : https://mulesoft.github.io/oas-raml-converter/
